{
 "title": "myk8sapp Grafana Dashboard",
 "description": "myk8sapp Grafana Dashboard",
 "tags": [
  "myk8sapp",
  "kubernetes-project"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "myk8sapp Pod Restart Count",
   "type": "timeseries",
   "description": "Displays the total number of container restarts for each myk8sapp pod in the dev namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  kube_pod_container_status_restarts_total{namespace=\"dev\", pod=~\"myk8sapp.*\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " myk8sapp Pod Status (Running by Pod)",
   "type": "timeseries",
   "description": "Shows whether each pod is in the Running phase, grouped by pod name.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  kube_pod_status_phase{namespace=\"dev\", phase=\"Running\", pod=~\"myk8sapp.*\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second by Pod",
   "type": "timeseries",
   "description": "Shows the per‑second rate of HTTP requests handled by each pod, grouped by pod label.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "timeseries",
   "description": "Displays the per‑second rate of incoming HTTP requests calculated over a 1‑minute window.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}