apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - name: https
    protocol: TCP
    port: {{ .Values.app.service.portnumber }}
    targetPort: {{ .Values.app.container1.portnumber }}