apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: {{ .Values.app.name }}-selfsigned-tls
spec:
 secretName: {{ .Values.app.name }}-tls-key-pair
 isCA: true
 issuerRef:
   name: {{ .Values.app.name }}-selfsigned-cluster-issuer
   kind: ClusterIssuer
 commonName: "ingress.com"
 dnsNames:
 - {{ .Values.app.name }}.ingress.com
 - ingress.com
