apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
data:
  config.properties: |
    property1={{ .Values.app.configmap.data.value1 }}
    property2={{ .Values.app.configmap.data.value2 }}