# In this Deployment YAML Manifest, common configuration tasks for Pods & Containers will be illustrated. 
#Source documentation: https://kubernetes.io/docs/tasks/configure-pod-container/


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  annotations:
    reloader.stakater.com/auto: "true"                  # required annotation for reloader
spec:
  replicas: {{ .Values.app.replicanumber }}
  selector:
    matchLabels:
      app:  {{ .Values.app.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1 # maxSure as an absolute number of replicas
      maxUnavailable: 33% #  maxUnavailable as % of replicas
    type: RollingUpdate
  minReadySeconds: 5 # Using minReadySeconds to add a readiness buffer.
  template:
    metadata:
      labels:
        app:  {{ .Values.app.name }}
    spec:
      initContainers:
      - name: {{ .Values.app.initcontainer.name }}-init-container
        image: "{{ .Values.app.initcontainer.image}}:{{ .Values.app.initcontainer.tag}}"
        command: ["sleep", "5"]
      - name: {{ .Values.app.nativesidecar.name }}-native-sidecar-container                #illustration of k8s native-sidecar container
        image: "{{ .Values.app.nativesidecar.image}}:{{ .Values.app.nativesidecar.tag}}"
        ports:
        - containerPort:  8082
        restartPolicy: Always                                 # To ensure the native sidecar starts before later containers are started                                            
        startupProbe:                                         # To ensure the init (native sidecar) Container is ready as main container won't start unless init container is up
          exec:
            command:
            - cat 
            - /fluentd/etc/fluent.conf
          failureThreshold: 30
          periodSeconds: 10
          successThreshold: 1
      containers:
      - name:  {{ .Values.app.container1.name }}-main-container
        image: "{{ .Values.app.container1.image}}:{{ .Values.app.container1.tag}}"
        ports:
        - containerPort:  {{ .Values.app.container1.portnumber }}
        resources:
          {{ .Values.app.resources | toYaml | nindent 10}}                 # Resources values will be fetched from values file to make the Pod QoS Burstable
        resizePolicy:                                                      # if desired requests or limits for both CPU and memory have changed, the container will not be restarted in order to resize its memory.
        - resourceName: memory                                             # Please note, for activation of this resizePolicy, the feature-gate InPlacePodVerticalScaling must remain enabled in kube-api server
          restartPolicy: NotRequired 
        - resourceName: cpu
          restartPolicy: NotRequired 
        env:
          - name: stage
            valueFrom: 
              configMapKeyRef:
                name: {{ .Values.app.name }}-config
                key: env
        readinessProbe: 
          exec: 
            command:
            - cat
            - /etc/resolv.conf
          initialDelayseconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: {{ .Values.app.container1.readinessprobe.successThreshold }}
          failureThreshold: {{ .Values.app.container1.readinessprobe.failureThreshold }}
        volumeMounts: 
          - mountPath: /mnt 
            name: {{ .Values.app.name }}-host-path-volume
      volumes:
        - name: {{ .Values.app.name }}-host-path-volume
          hostPath: 
            path: /tmp
            type: Directory