apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  annotations:
    cert-manager.io/clusterissuer: "{{ .Values.app.name }}-selfsigned-cluster-issuer"   #annotation reference of cluster-issuer
    ingress.kubernetes.io/ssl-redirect: "true"    #annotation for redirection over HTTPS
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ .Values.app.name }}.ingress.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}-service
            port: 
              number: {{ .Values.app.service.portnumber }}
    tls:
      - hosts: 
        - {{ .Values.app.name }}.ingress.com
        secretName: {{ .Values.app.name }}-tls-key-pair