apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: myk8sapp-networkpolicy
  namespace: dev
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 127.0.0.1/32
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
