apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-kube-prometheus-prometheus-ingress
  namespace: default  #must be the same namespace where kube-prometheus stack is installed
spec:
  ingressClassName: "nginx"
  rules:
  - host: prometheus.ingress.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port: 
              number: 9090