apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-kube-prometheus-prometheus-ingress
  namespace: prometheus  #must be the same namespace where kube-prometheus stack is installed
spec:
  {{ .Values.prometheusIngressSpec | toYaml | nindent 2 }}