apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-grafana-ingress
  namespace: prometheus  #must be the same namespace where kube-prometheus stack is installed
spec:
  {{ .Values.prometheusGrafanaIngressSpec | toYaml | nindent 2}}