# Default values for myk8sapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: myk8sapp-dev
  configmap:
    data:
      customheader:
        value: "custom value for dev"
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"