# Default values for myk8sapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: myk8sapp-dev
  configmap:
    data:
      env: "This is DEV env"  
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"
  container1:
    readinessprobe:
      initialDelayseconds: 5
      successThreshold: 1
      failureThreshold: 1

db:
  container1:
    readinessprobe:
      initialDelayseconds: 3
      successThreshold: 2
      failureThreshold: 1