# Default values for myk8sapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: myk8sapp-prod
  configmap:
    data:
      customheader:
        value: "custom value for prod"