# Default values for myk8sapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicanumber: 1
  initcontainer:
    name: httpd
    portnumber: 80
    image: httpd
    tag: latest
  container1:
    name: test-prometheus-app
    portnumber: 8080
    image: quay.io/brancz/prometheus-example-app
    tag: v0.3.0
    readinessprobe:
      initialDelayseconds: 10
      successThreshold: 1
      failureThreshold: 1
  container2:
    name: fluentd
    portnumber: 8082
    image: fluentd
    tag: latest
  service:
    portnumber: 80
  resources:
    limits:
      memory: "320Mi"
      cpu: "600m"
    requests:
      memory: "256Mi"
      cpu: "500m"
  configmap:
    data:
      env: "stage specific dynamically overridden from respective value file"

db:
  replicanumber: 1
  container1:
    image: mongo
    portnumber: 27017

