# Default values for myk8sapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: myk8sapp
  replicanumber: 2
  image:
    name: nginx
    tag: latest
  container:
    portnumber: 8080
  service:
    portnumber: 8080
  resources:
    limits:
      memory: "320Mi"
      cpu: "600m"
    requests:
      memory: "256Mi"
      cpu: "500m"
  configmap:
    data:
      configproperties:
        value1: white
        value2: no color
      customheader:
        value: custom-header
