# Default values for myk8sapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app: 
  name: myk8sapp
  annotation: 'reloader.stakater.com/auto: "true"'
  replicanumber: 1
  initcontainer:
    name: httpd
    portnumber: 80
    image: httpd
    tag: latest
  container1:
    name: test-prometheus-app
    portnumber: 8080
    image: quay.io/brancz/prometheus-example-app
    tag: v0.3.0
    readinessprobe:
      initialDelayseconds: 10
      successThreshold: 1
      failureThreshold: 1
  nativesidecar:
    name: fluentd
    portnumber: 8082
    image: fluentd
    tag: latest
  service:
    portnumber: 8443
  resources:
    limits:
      memory: 320Mi
      cpu: 600m
    requests:
      memory: 256Mi
      cpu: 500m
  configmap:
    data:
      env: "testing the changes detectable by reloader"

db:
  name: myk8sappdb
  replicanumber: 1
  container1:
    image: mongo
    portnumber: 27017

prometheusIngressSpec:
  ingressClassName: "nginx"
  rules:
  - host: prometheus.ingress.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port: 
              number: 9090

argocdServerIngressSpec:
  ingressClassName: "nginx"
  rules:
  - host: argocd-server.ingress.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443

prometheusGrafanaIngressSpec:
  ingressClassName: "nginx"
  rules:
  - host: prometheus-grafana.ingress.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port: 
              number: 80

prometheusExporterIngressSpec:
  ingressClassName: "nginx"
  rules:
  - host: prometheus-myk8sappdb-exporter.ingress.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-exporter-prometheus-mongodb-exporter
            port: 
              number: 9216